spring:
  application:
    name: book-service

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices_demo_books_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

  http:
    encoding:
      charset: UTF-8
      enabled: true
  flyway:
    enabled: true
    locations: classpath:flyway

server:
  port: 8002

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true
