spring:
  application:
    name: zuul-service



server:
  port: 8010

logging:
  level:
    org.springframework.web: DEBUG

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

zuul:
  routes:
    book-service:
      path: /book-service/**
      url: http://localhost:8002/api
      serviceId: BOOK-SERVICE
    music-service:
      path: /music-service/**
      url: http://localhost:8003/api
      serviceId: MUSIC-SERVICE
  ignored-services: '*'
